### ISSUE TITLE
200kB send traffic from hwinfo plugin

### ISSUE THREAD

**Issue by NeonWizard** [shayne/hwinfo-streamdeck#25]
![image](https://user-images.githubusercontent.com/1355586/97266306-de591480-17ed-11eb-932b-b56828f467a5.png)
My network has been stuttering today and I opened resmon to check out what could cause it. Right at the top of the processes using upload bandwidth is the hwinfo streamdeck plugin. I have no idea why this plugin needs to upload anything in the first place, let alone 200k bytes/sec. Is this a rat? @shayne

**Comment by shayne** [comment]
The plug-in communicates with the stream deck via sdk over localhost. All plugins communicate this way. It's a local web api that the sdk provides. 

The throughput you're seeing is 200kB. This contains the graphs that are sent up through the sdk. It is rather small and again, it's all local. 

The performance monitor can show you the connections made and you should see the web socket that the sdk provides. You can also verify with elgato on their docs site or directly. 

The reason this is closed source, for now, is to respect the author of HWiNFO. That said, I have broken it up and separated the plug-in from the hardware service. Will release this code and update soon. Life stuff rn. 

Happy to respond to any other questions or concerns.

**Comment by shayne** [comment]
Here's a screenshot of Performance Monitor on my machine showing the loopback/local connections. You should be able to see it on yours as well.

I'm running the split-out version I was talking about so there's two processes, `hwinfo.exe` that talks to the Stream Deck SDK and `hwinfo-plugin.exe` that talks to HWiNFO. 

Also, I'm pushing closer to 300K. This makes sense because I'm rendering 14 graphs, each is 72x72 pixels, 4 bytes per pixel (RGBA) == 290K plus some PNG and SDK overhead.

This is a relatively small amount of bandwidth, but also moot given it's loopback/local. It's using the same interface that's providing you internet.

![image](https://user-images.githubusercontent.com/79330/97317900-8be91980-1828-11eb-92e1-e35afe69ad06.png)

**Comment by NeonWizard** [comment]
Thanks for the info.
