### ISSUE TITLE
Not working with HWINFO pro v7.07-4505

### ISSUE THREAD

**Issue by percusswords** [shayne/hwinfo-streamdeck#39]
After updating HWINFO, even with shared memory enabled and everything else as recommended, the Stream Deck keeps saying to "Please Launch HWINFO64"

**Comment by darkynt** [comment]
also observed; it was working with non-pro, I upgraded to pro then HWInfo prompted me to update the version to v7.07-4505, now this plugin doesn't seem to work.

**Comment by kaosfere** [comment]
Can confirm also not working with 7.06-4500, was working with prior versions of Pro.

**Comment by waynieoaks** [comment]
This was working for me after upgrading to pro. 
Just been prompted to upgrade to 7.10-4540 and I now have this same issue. 
Checked settings - rebooted - not detecting hwinfo

**Comment by Chloe-ko** [comment]
I just encountered the same issue and I think this happens if you use the built-in updater HWiNFO has.
The README does state that it does not work with the portable version. What I assume is that the built-in updater replaces itself using the portable binary.

Uninstalling hwinfo and reinstalling using the installer fixed this issue for me.

**Comment by Iunchbox** [comment]
@percusswords uninstall and reinstall worked for me. I would suggest marking this as solved.
